services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile_frontend_production
    ports:
      - "3000:3000"
