services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEBUG_DEPENDENCIES: "true"
    environment:
      DEBUGGER: ${DEBUGGER}
    ports:
      - "8000:8000"
      - "10001:10001"
    volumes:
      - ./app:/app/app
    command: uvicorn app.main:app --host "0.0.0.0" --port 8000 --reload
